#---
#- name: Pull Docker Image of Calculator
#  hosts: all
#  vars:
#    ansible_python_interpreter: /usr/bin/python3
#  tasks:
#    - name: Pull image
#      docker_image:
#        name: sahithi008/calculator:latest
#        source: pull
#    - name: Start docker service
#      service:
#        name: docker
#        state: started
#        - name: Running container
#          shell: docker run -it -d --name calculator sahithi008/calculator
---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      shell: docker pull sahithi008/calculator:latest
    - name: Running container
      # shell: docker run -it -d --name calculator sahithi008/calculator
      command: docker create -it --name calculator sahithi08/calculator